buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:5.1.+'
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'org.spongepowered.mixin'
apply plugin: 'java'

def properties = new Properties()
file('../../gradle.properties').withInputStream { properties.load(it) }
file('gradle.properties').withInputStream { properties.load(it) }
properties.each { key, value -> ext.set(key.toString(), value.toString()) }

group = mod_group_id
version = mod_version

archivesBaseName = "${mod_name}-forge-1.19.2"

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

minecraft {
    mappings channel: forge_1192_mapping_channel, version: forge_1192_mapping_version
    runs {
        client {
            workingDirectory project.file('run')
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file('run')
            args '--nogui'
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
    }
}

mixin {
    add sourceSets.main, "${mod_id}.forge1192.refmap.json"
    config "${mod_id}.forge1192.mixins.json"
}

repositories {
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    mavenCentral()
}

dependencies {
    minecraft "net.minecraftforge:forge:${forge_1192_minecraft_version}-${forge_1192_version}"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

tasks.named('processResources', ProcessResources).configure {
    def replaceProperties = [
            minecraft_version: forge_1192_minecraft_version,
            minecraft_version_range: forge_1192_minecraft_version_range,
            forge_version: forge_1192_version,
            forge_version_range: forge_1192_version_range,
            loader_version_range: forge_1192_loader_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version,
            mod_authors: mod_authors,
            mod_description: mod_description
    ]
    inputs.properties replaceProperties
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes('MixinConfigs': "${mod_id}.forge1192.mixins.json")
    }
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

apply from: file('../../gradle/target-conventions/target.gradle')
