modLoader = "javafml"
loaderVersion = "[4,)"
license = "GNU GPL 3.0"

[[mods]]
modId = "strikeafterswing"
version = "1.0.0"
displayName = "StrikeAfterSwing"
authors = "Tower of Sighs"
description = '''None'''

[[mixins]]
config = "strikeafterswing.neoforge.mixins.json"

[[dependencies.strikeafterswing]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.strikeafterswing]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,26.3)"
ordering = "NONE"
side = "BOTH"
